// LIVE per-project database — the leap from "ships a schema file" to "the app runs on a real DB".
// Each project's tables live in their OWN Postgres schema `app_<hex>`, NEVER `public`. Every operation
// is namespace-isolated, identifier-validated, and parameterized, so a produced app's data model is real
// and queryable while the engine's tables (public) can never be touched. This is the safety contract:
// the only schema we ever create/drop/write is `app_<32hex>` derived from the project UUID.
import pg from 'pg';
import { parseModel, compile, lit } from './schema.ts';

const IDENT = /^[a-z_][a-z0-9_]*$/;            // a legal, safe SQL identifier (no quoting tricks)

// app_<32 hex of the project uuid>. Throws on anything that wouldn't be exactly this — so we can NEVER
// accidentally operate on `public`, an empty name, or an injected identifier.
export function schemaName(projectId: string): string {
  const hex = String(projectId || '').toLowerCase().replace(/[^a-f0-9]/g, '');
  if (hex.length < 16) throw new Error('appdb: refusing — project id too short to namespace: ' + projectId);
  const name = 'app_' + hex.slice(0, 32);
  if (!/^app_[a-f0-9]{16,32}$/.test(name)) throw new Error('appdb: bad schema name ' + name);
  return name;
}

const stripFences = (s: string) => s.replace(/```[a-zA-Z]*\n?/g, '').replace(/```/g, '').trim();
function sqlBody(content: string): string { const s = stripFences(content); const at = s.search(/create\s+table/i); return at >= 0 ? s.slice(at) : s; }

// Strip SQL comments and normalize whitespace (incl. around dots) so the confinement denylist can't be
// fooled by `public /* */ . foo`, `copy\nfrom`, or `set/**/role`. The SANITIZED text is what we both
// validate AND execute, so what passes the check is exactly what runs.
function sanitizeDdl(content: string): string {
  return sqlBody(content)
    .replace(/\/\*[\s\S]*?\*\//g, ' ')   // /* block comments */
    .replace(/--[^\n]*/g, ' ')           // -- line comments
    .replace(/\s+/g, ' ')                // collapse whitespace/newlines
    .replace(/\s*\.\s*/g, '.')           // "public . foo" / "public/**/.foo" -> "public.foo"
    .trim();
}

// Reject any DDL that could escape the project's schema or touch the engine. Generated app DDL never
// legitimately references another schema or session settings — so blocking these is free safety.
function assertConfined(ddl: string) {
  const lower = ddl.toLowerCase();
  // the engine pool is a superuser, so block anything beyond plain tables/indexes/inserts: cross-schema
  // refs, session settings, procedural/privilege/extension constructs, and IO functions.
  for (const bad of ['public.', 'pg_catalog', 'pg_class', 'information_schema', 'search_path', 'set role',
    'set session', 'create schema', 'drop schema', 'drop database', 'alter system', '\\connect', 'dblink',
    'copy ', 'pg_read', 'pg_sleep', 'create extension', 'create or replace', 'create function',
    'create trigger', 'create policy', 'security definer', 'grant ', 'revoke ', 'alter role', 'alter user'])
    if (lower.includes(bad)) throw new Error('appdb: schema DDL contains a disallowed construct: ' + bad.trim());
}

const SENSITIVE = /pass|secret|token|hash|salt|api_?key|private|credential/i;   // never expose these via the public read API

// Provision the project's schema FOR REAL: drop+recreate its isolated namespace and apply the DDL (+ any
// seed INSERTs) inside it. Idempotent — a rebuild re-provisions cleanly. Returns the tables that now exist.
// The agent's DB output -> final DDL: a JSON data-model is COMPILED into perfect, consistent Postgres
// (PKs, FK indexes, types, defaults); raw SQL falls back to the sanitized+confined path (legacy).
export function compileDDL(content: string): { ddl: string; warnings: string[] } {
  const model = parseModel(content);
  if (model) { const c = compile(model); return { ddl: c.ddl, warnings: c.warnings }; }   // generated by us -> trusted
  const ddl = sanitizeDdl(content); assertConfined(ddl); return { ddl, warnings: [] };       // raw SQL -> confine
}

export async function provision(pool: pg.Pool, projectId: string, content: string): Promise<{ schema: string; tables: string[]; migration?: { applied: string[]; skipped: string[] } }> {
  const schema = schemaName(projectId);
  const { ddl } = compileDDL(content);
  if (!/create\s+table/i.test(ddl)) throw new Error('appdb: no tables in the data model / schema output');
  // IDEMPOTENT + non-destructive. A provisioned schema is never re-dropped; on a REBUILD (M3) the
  // new model is MIGRATED onto it: missing tables created (+seeded), missing columns added — rows
  // always survive (a row-count guard rolls the whole migration back if any table loses data).
  const existing = await listTables(pool, projectId);
  if (existing.length) {
    const migration = await migrate(pool, projectId, content, existing);
    return { schema, tables: await listTables(pool, projectId), migration };
  }
  const c = await pool.connect();
  try {
    await c.query('begin');
    await c.query("set local statement_timeout = '15s'");           // bound pathological/runaway DDL
    await c.query(`create schema if not exists "${schema}"`);        // never public; safe under concurrency
    await c.query(`set local search_path to "${schema}"`);           // unqualified CREATE/INSERT land HERE; tx-scoped
    await c.query(ddl);
    await c.query('commit');
  } catch (e) { try { await c.query('rollback'); } catch {} throw e; }
  finally { c.release(); }
  return { schema, tables: await listTables(pool, projectId) };
}

// M3 — SAFE SCHEMA MIGRATION. Diff the new model against the live catalog and apply ONLY additive,
// data-preserving changes: new tables (with their indexes + seeds), new columns (with a sensible
// default so NOT NULL holds on populated tables; relations stay nullable — a guess would be a lie).
// NEVER drops or retypes anything; a type drift is reported and the stored type kept. The whole
// migration runs in ONE transaction with a row-count guard: if any pre-existing table would end up
// with fewer rows, everything rolls back.
const typeDefault = (t: string): string | null =>
  t === 'boolean' ? 'false'
  : /^(integer|numeric)/.test(t) ? '0'
  : t === 'date' || t === 'timestamptz' || /^timestamp/.test(t) ? 'now()'
  : t === 'jsonb' ? `'{}'::jsonb`
  : t === 'text' ? `''`
  : null;
// information_schema data_type -> our compiled type family, for drift comparison
const typeFamily = (t: string): string =>
  /char|text/.test(t) ? 'text' : /^(int|integer|bigint|smallint)/.test(t) ? 'integer'
  : /numeric|decimal|real|double/.test(t) ? 'numeric' : /bool/.test(t) ? 'boolean'
  : /timestamp/.test(t) ? 'timestamptz' : /^date$/.test(t) ? 'date' : /json/.test(t) ? 'jsonb' : t;

export async function migrate(pool: pg.Pool, projectId: string, content: string, existing: string[]): Promise<{ applied: string[]; skipped: string[] }> {
  const schema = schemaName(projectId);
  const model = parseModel(content);
  const applied: string[] = [], skipped: string[] = [];
  if (!model) { skipped.push('raw-SQL model — migration unsupported, existing schema left untouched'); return { applied, skipped }; }
  const { resolved } = compile(model);
  const stmts: string[] = [];
  for (const t of resolved.order) {
    if (!existing.includes(t)) {
      stmts.push(resolved.createSql[t], ...resolved.indexSql[t], ...resolved.seedSql[t]);
      applied.push(`+table "${t}" (${resolved.seedSql[t].length} seed rows)`);
      continue;
    }
    const have = new Map((await typedColumns(pool, schema, t)).map(c => [c.name, c]));
    for (const c of resolved.cols[t]) {
      const cur = have.get(c.name);
      if (cur) {
        if (typeFamily(cur.type) !== typeFamily(c.type)) skipped.push(`~"${t}"."${c.name}": kept ${cur.type} (model wants ${c.type} — retype would risk data)`);
        continue;
      }
      if (c.ref) {
        // a new relation on a populated table stays NULLABLE — inventing FK values would be a lie
        const refExists = existing.includes(c.ref) || resolved.order.includes(c.ref);
        stmts.push(`alter table "${t}" add column "${c.name}" integer${refExists ? ` references "${c.ref}"(id) on delete set null` : ''};`);
        if (refExists) stmts.push(`create index "${t}_${c.name}_idx" on "${t}" ("${c.name}");`);
        applied.push(`+"${t}"."${c.name}" (relation → ${c.ref}, nullable)`);
        if (c.required) skipped.push(`~"${t}"."${c.name}": required relation added as nullable — existing rows can't be guessed`);
        continue;
      }
      const def = c.def !== undefined ? lit(c.def, c.type) : typeDefault(c.type);
      let sql = `alter table "${t}" add column "${c.name}" ${c.type}`;
      if (def !== null && def !== 'null') sql += ` default ${def}`;
      stmts.push(sql + ';');
      if (c.required && def !== null && def !== 'null') stmts.push(`alter table "${t}" alter column "${c.name}" set not null;`);
      applied.push(`+"${t}"."${c.name}" ${c.type}${def && def !== 'null' ? ` default ${def}` : ''}`);
    }
  }
  if (!stmts.length) return { applied, skipped };
  const before = new Map<string, number>();
  for (const t of existing) before.set(t, Number((await pool.query(`select count(*)::int n from "${schema}"."${t}"`)).rows[0].n));
  const c = await pool.connect();
  try {
    await c.query('begin');
    await c.query("set local statement_timeout = '15s'");
    await c.query(`set local search_path to "${schema}"`);
    for (const s of stmts) await c.query(s);
    for (const [t, n] of before) {
      const now = Number((await c.query(`select count(*)::int n from "${schema}"."${t}"`)).rows[0].n);
      if (now < n) throw new Error(`migration guard: "${t}" would lose rows (${n} → ${now}) — rolled back`);
    }
    await c.query('commit');
  } catch (e) { try { await c.query('rollback'); } catch {} throw e; }
  finally { c.release(); }
  return { applied, skipped };
}

// PQ2 — PLACE ORDER: the checkout write. Deterministic store contract: tables literally named
// products / orders / order_items (enforced by the app_db gate for store briefs). ZERO TRUST in the
// client: prices come from the products table, the total is computed HERE, unit prices are
// snapshotted onto the line items, and the whole write is one transaction.
export async function placeOrder(pool: pg.Pool, projectId: string, buyer: Record<string, any>, items: { id: any; qty: any }[]): Promise<{ ok: boolean; order?: number; total?: number; error?: string }> {
  const schema = schemaName(projectId);
  const tables = await listTables(pool, projectId);
  for (const t of ['products', 'orders', 'order_items']) if (!tables.includes(t)) return { ok: false, error: 'this site has no store (missing ' + t + ')' };
  // validate items: 1..30 lines, integer ids, qty 1..99, no duplicates
  if (!Array.isArray(items) || !items.length || items.length > 30) return { ok: false, error: 'cart is empty or too large' };
  const seen = new Set<number>();
  const lines: { id: number; qty: number }[] = [];
  for (const it of items) {
    const id = Number(it?.id), qty = Number(it?.qty);
    if (!Number.isInteger(id) || id < 1 || !Number.isInteger(qty) || qty < 1 || qty > 99 || seen.has(id)) return { ok: false, error: 'invalid cart line' };
    seen.add(id); lines.push({ id, qty });
  }
  const name = String(buyer?.customer_name ?? buyer?.name ?? '').trim();
  const email = String(buyer?.email ?? '').trim();
  if (!name || name.length > 120) return { ok: false, error: 'your name is required' };
  if (!/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(email)) return { ok: false, error: 'a real email is required' };
  // server-side pricing — the client\'s numbers are never used
  const priceCols = (await typedColumns(pool, schema, 'products')).filter(c => /numeric|int|real|double|decimal/.test(c.type) && /^(price|amount|cost)$/.test(c.name));
  if (!priceCols.length) return { ok: false, error: 'products table has no price column' };
  const pcol = priceCols[0].name;
  const prod = await pool.query(`select id, "${pcol}"::numeric as price from "${schema}"."products" where id = any($1)`, [lines.map(l => l.id)]);
  const priceById = new Map<number, number>(prod.rows.map((r: any) => [Number(r.id), Number(r.price)]));
  for (const l of lines) if (!priceById.has(l.id)) return { ok: false, error: 'a product in your cart no longer exists' };
  const total = Math.round(lines.reduce((s2, l) => s2 + priceById.get(l.id)! * l.qty, 0) * 100) / 100;
  // column-flexible write (the model may name columns slightly differently), one transaction
  const oCols = new Set((await typedColumns(pool, schema, 'orders')).map(c => c.name));
  const iCols = new Set((await typedColumns(pool, schema, 'order_items')).map(c => c.name));
  const nameCol = ['customer_name', 'name', 'buyer_name'].find(c => oCols.has(c));
  const qtyCol = ['qty', 'quantity'].find(c => iCols.has(c));
  const unitCol = ['unit_price', 'price'].find(c => iCols.has(c));
  const prodCol = ['product_id'].find(c => iCols.has(c));
  const orderCol = ['order_id'].find(c => iCols.has(c));
  if (!nameCol || !qtyCol || !prodCol || !orderCol) return { ok: false, error: 'store schema is missing standard order columns' };
  const c = await pool.connect();
  try {
    await c.query('begin');
    await c.query("set local statement_timeout = '10s'");
    const cols: string[] = [nameCol]; const vals: any[] = [name];
    if (oCols.has('email')) { cols.push('email'); vals.push(email); }
    if (oCols.has('phone') && buyer?.phone) { cols.push('phone'); vals.push(String(buyer.phone).slice(0, 40)); }
    if (oCols.has('notes') && buyer?.notes) { cols.push('notes'); vals.push(String(buyer.notes).slice(0, 500)); }
    if (oCols.has('status')) { cols.push('status'); vals.push('new'); }
    if (oCols.has('total')) { cols.push('total'); vals.push(total); }
    const o = await c.query(`insert into "${schema}"."orders" (${cols.map(x => `"${x}"`).join(',')}) values (${cols.map((_, i) => '$' + (i + 1)).join(',')}) returning id`, vals);
    const orderId = Number(o.rows[0].id);
    for (const l of lines) {
      const ic: string[] = [orderCol, prodCol, qtyCol]; const iv: any[] = [orderId, l.id, l.qty];
      if (unitCol) { ic.push(unitCol); iv.push(priceById.get(l.id)); }
      await c.query(`insert into "${schema}"."order_items" (${ic.map(x => `"${x}"`).join(',')}) values (${ic.map((_, i) => '$' + (i + 1)).join(',')})`, iv);
    }
    await c.query('commit');
    return { ok: true, order: orderId, total };
  } catch (e: any) {
    try { await c.query('rollback'); } catch {}
    console.error('placeOrder', projectId, e?.message ?? e);
    return { ok: false, error: 'could not place the order — please try again' };
  } finally { c.release(); }
}

export async function listTables(pool: pg.Pool, projectId: string): Promise<string[]> {
  const schema = schemaName(projectId);
  const r = await pool.query(
    "select table_name from information_schema.tables where table_schema=$1 and table_type='BASE TABLE' order by table_name", [schema]);
  return r.rows.map((x: any) => x.table_name);
}

async function typedColumns(pool: pg.Pool, schema: string, table: string): Promise<{ name: string; type: string; nullable: boolean }[]> {
  const r = await pool.query('select column_name, data_type, is_nullable from information_schema.columns where table_schema=$1 and table_name=$2 order by ordinal_position', [schema, table]);
  return r.rows.map((x: any) => ({ name: x.column_name, type: x.data_type, nullable: x.is_nullable === 'YES' }));
}
// coerce a posted string to the column's real type (so a numeric/boolean column stores correctly)
function coerce(v: any, type: string): any {
  if (v === '' || v === null || v === undefined) return null;
  if (/bool/.test(type)) return v === true || /^(true|on|1|yes)$/i.test(String(v));
  if (/int|numeric|real|double|decimal/.test(type)) { const n = Number(v); return Number.isFinite(n) ? n : null; }
  return String(v);
}

// pick a human display column for a table: name/title/label, else the first text column, else id
async function displayColumn(pool: pg.Pool, schema: string, table: string): Promise<string> {
  const cols = await typedColumns(pool, schema, table);
  const pref = cols.find(c => ['name', 'title', 'label'].includes(c.name));
  if (pref) return pref.name;
  const txt = cols.find(c => /char|text/.test(c.type) && c.name !== 'id');
  return txt ? txt.name : 'id';
}

// Read rows from a REAL project table (validated against the schema's own catalog; never arbitrary SQL).
// RELATION-AWARE: each FK column (x_id -> table y) is resolved to y's display value and exposed as `x`,
// so a collection shows "Category: Ceramics", not "category_id: 3". Secrets are stripped.
export async function readRows(pool: pg.Pool, projectId: string, table: string, limit = 50): Promise<any[]> {
  const schema = schemaName(projectId);
  if (!IDENT.test(table)) return [];
  const tables = await listTables(pool, projectId);
  if (!tables.includes(table)) return [];
  const lim = Math.max(1, Math.min(200, Number(limit) || 50));
  const rows = (await pool.query(`select * from "${schema}"."${table}" order by id desc limit ${lim}`)).rows;
  try {
    const fks = (await pool.query(
      `select kcu.column_name as col, ccu.table_name as ref
       from information_schema.table_constraints tc
       join information_schema.key_column_usage kcu on kcu.constraint_name=tc.constraint_name and kcu.table_schema=tc.table_schema
       join information_schema.constraint_column_usage ccu on ccu.constraint_name=tc.constraint_name and ccu.table_schema=tc.table_schema
       where tc.constraint_type='FOREIGN KEY' and tc.table_schema=$1 and tc.table_name=$2`, [schema, table])).rows;
    for (const fk of fks) {
      if (!IDENT.test(fk.col) || !IDENT.test(fk.ref) || !tables.includes(fk.ref)) continue;
      const ids = [...new Set(rows.map((r: any) => r[fk.col]).filter((v: any) => v != null))];
      if (!ids.length) continue;
      const dcol = await displayColumn(pool, schema, fk.ref);
      if (!IDENT.test(dcol)) continue;
      const map = new Map((await pool.query(`select id, "${dcol}" as d from "${schema}"."${fk.ref}" where id = any($1)`, [ids])).rows.map((r: any) => [r.id, r.d]));
      const label = fk.col.replace(/_id$/, '');
      for (const r of rows) { r[label] = map.get(r[fk.col]) ?? null; delete r[fk.col]; }
    }
  } catch {}
  return rows.map((row: any) => { const o = { ...row }; for (const k of Object.keys(o)) if (SENSITIVE.test(k)) delete o[k]; return o; });
}

// Insert one row into a REAL project table — only existing columns, type-coerced, fully parameterized.
export async function insertRow(pool: pg.Pool, projectId: string, table: string, data: Record<string, any>): Promise<boolean> {
  const schema = schemaName(projectId);
  if (!IDENT.test(table)) return false;
  if (!(await listTables(pool, projectId)).includes(table)) return false;
  const use = (await typedColumns(pool, schema, table)).filter(c => IDENT.test(c.name) && c.name in (data || {}) && !['id', 'created_at'].includes(c.name) && !SENSITIVE.test(c.name));
  if (!use.length) return false;
  const vals = use.map((_, i) => '$' + (i + 1));
  await pool.query(`insert into "${schema}"."${table}" (${use.map(c => `"${c.name}"`).join(',')}) values (${vals.join(',')})`,
    use.map(c => coerce(data[c.name], c.type)));
  return true;
}

// PQ3 — CLIENT CONTENT EDITING. Directus lives in a SEPARATE database and cannot reach the app_<hex>
// schema (that's where products/menu/posts really live), so the owner edits their content through
// Relay's own owner-scoped admin over THIS API. The live site already reads these tables live, so an
// edit shows immediately. Same safety contract as insert/read: namespace-confined, identifier-checked,
// parameterized, type-coerced, secret columns never touched.

// System tables the client should NOT hand-edit as "content": join/system/transactional tables and
// anything with no human-meaningful display column. Everything else (products, menu, posts, team…) is
// editable content the client owns.
const CONTENT_HIDDEN = /^(order_items|orders|submissions|sessions|auth|tokens?|migrations?|users?|accounts?)$/i;

// The editable content collections of a site — the "Products / Menu / Posts" a client manages.
export async function contentTables(pool: pg.Pool, projectId: string): Promise<{ table: string; label: string; rows: number; display: string }[]> {
  const schema = schemaName(projectId);
  const out: { table: string; label: string; rows: number; display: string }[] = [];
  for (const t of await listTables(pool, projectId)) {
    if (CONTENT_HIDDEN.test(t)) continue;
    const disp = await displayColumn(pool, schema, t);
    if (disp === 'id') continue;   // no human handle -> not client-facing content
    let rows = 0; try { rows = Number((await pool.query(`select count(*)::int n from "${schema}"."${t}"`)).rows[0].n); } catch {}
    out.push({ table: t, label: t.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase()), rows, display: disp });
  }
  return out;
}

// One record by id (secret columns stripped) — for the edit form.
export async function getRow(pool: pg.Pool, projectId: string, table: string, id: number): Promise<any | null> {
  const schema = schemaName(projectId);
  if (!IDENT.test(table) || !Number.isInteger(id) || !(await listTables(pool, projectId)).includes(table)) return null;
  const r = (await pool.query(`select * from "${schema}"."${table}" where id=$1`, [id])).rows[0];
  if (!r) return null;
  const o = { ...r }; for (const k of Object.keys(o)) if (SENSITIVE.test(k)) delete o[k];
  return o;
}

// UPDATE a record — only real, non-system columns the caller supplied; type-coerced; id/created_at and
// secret columns can never be written. Returns false if the table/row/columns don't validate.
export async function updateRow(pool: pg.Pool, projectId: string, table: string, id: number, data: Record<string, any>): Promise<boolean> {
  const schema = schemaName(projectId);
  if (!IDENT.test(table) || !Number.isInteger(id) || !(await listTables(pool, projectId)).includes(table)) return false;
  const use = (await typedColumns(pool, schema, table)).filter(c => IDENT.test(c.name) && c.name in (data || {}) && !['id', 'created_at'].includes(c.name) && !SENSITIVE.test(c.name));
  if (!use.length) return false;
  const set = use.map((c, i) => `"${c.name}"=$${i + 1}`).join(',');
  const r = await pool.query(`update "${schema}"."${table}" set ${set} where id=$${use.length + 1}`,
    [...use.map(c => coerce(data[c.name], c.type)), id]);
  return (r.rowCount ?? 0) > 0;
}

// DELETE a record. Confined to the project schema; parameterized id.
export async function deleteRow(pool: pg.Pool, projectId: string, table: string, id: number): Promise<boolean> {
  const schema = schemaName(projectId);
  if (!IDENT.test(table) || !Number.isInteger(id) || !(await listTables(pool, projectId)).includes(table)) return false;
  const r = await pool.query(`delete from "${schema}"."${table}" where id=$1`, [id]);
  return (r.rowCount ?? 0) > 0;
}

// Columns of a table suitable for an "add a record" form: scalar user-fillable fields PLUS real
// relations (M2): a column with an actual FK constraint is returned with {ref, display} so the
// renderer emits a <select> of the referenced table's real records — the form matches the schema
// by construction, never hand-emitted. Non-FK `*_id` columns stay hidden (opaque numbers).
export async function formColumns(pool: pg.Pool, projectId: string, table: string): Promise<{ name: string; type: string; nullable: boolean; ref?: string; display?: string }[]> {
  const schema = schemaName(projectId);
  if (!IDENT.test(table) || !(await listTables(pool, projectId)).includes(table)) return [];
  const fkMap = new Map<string, string>();
  try {
    const fks = (await pool.query(
      `select kcu.column_name as col, ccu.table_name as ref
       from information_schema.table_constraints tc
       join information_schema.key_column_usage kcu on kcu.constraint_name=tc.constraint_name and kcu.table_schema=tc.table_schema
       join information_schema.constraint_column_usage ccu on ccu.constraint_name=tc.constraint_name and ccu.table_schema=tc.table_schema
       where tc.constraint_type='FOREIGN KEY' and tc.table_schema=$1 and tc.table_name=$2`, [schema, table])).rows;
    for (const fk of fks) if (IDENT.test(fk.col) && IDENT.test(fk.ref) && fk.ref !== table) fkMap.set(fk.col, fk.ref);
  } catch {}
  const out: { name: string; type: string; nullable: boolean; ref?: string; display?: string }[] = [];
  for (const c of await typedColumns(pool, schema, table)) {
    if (['id', 'created_at'].includes(c.name) || SENSITIVE.test(c.name)) continue;
    const ref = fkMap.get(c.name);
    if (ref) out.push({ ...c, ref, display: await displayColumn(pool, schema, ref) });
    else if (!/_id$/.test(c.name)) out.push(c);
  }
  return out;
}

// INTROSPECTION — the system knows the database: every table's columns/types, real relations, row counts.
// Read straight from the catalog of the project's own schema. Powers the data API, the build agent, and
// the project workspace's "Database" view.
export async function describeSchema(pool: pg.Pool, projectId: string): Promise<{ schema: string; tables: any[] }> {
  const schema = schemaName(projectId);
  const tabs = await listTables(pool, projectId);
  const tables: any[] = [];
  for (const t of tabs) {
    const cols = (await pool.query(
      'select column_name, data_type, is_nullable from information_schema.columns where table_schema=$1 and table_name=$2 order by ordinal_position', [schema, t])).rows;
    const fks = (await pool.query(
      `select kcu.column_name as col, ccu.table_name as ref
       from information_schema.table_constraints tc
       join information_schema.key_column_usage kcu on kcu.constraint_name=tc.constraint_name and kcu.table_schema=tc.table_schema
       join information_schema.constraint_column_usage ccu on ccu.constraint_name=tc.constraint_name and ccu.table_schema=tc.table_schema
       where tc.constraint_type='FOREIGN KEY' and tc.table_schema=$1 and tc.table_name=$2`, [schema, t])).rows;
    let rows = 0; try { rows = Number((await pool.query(`select count(*)::int n from "${schema}"."${t}"`)).rows[0].n); } catch {}
    tables.push({
      table: t, rows,
      columns: cols.map((c: any) => ({ name: c.column_name, type: c.data_type, nullable: c.is_nullable === 'YES' })),
      relations: fks.map((f: any) => ({ column: f.col, references: f.ref })),
    });
  }
  return { schema, tables };
}
