// LIVE per-project database — the leap from "ships a schema file" to "the app runs on a real DB".
import { L, columnLabel } from './i18n.ts';
// Each project's tables live in their OWN Postgres schema `app_<hex>`, NEVER `public`. Every operation
// is namespace-isolated, identifier-validated, and parameterized, so a produced app's data model is real
// and queryable while the engine's tables (public) can never be touched. This is the safety contract:
// the only schema we ever create/drop/write is `app_<32hex>` derived from the project UUID.
import pg from 'pg';
import { randomBytes } from 'node:crypto';
import { parseModel, compile, lit, PRIVATE_READ, LIFECYCLE_TABLE, STATUS_SET, SLOT_TABLE } from './schema.ts';
import { localRowImage } from './rowmedia.ts';

// FS0 — who is reading? 'public' = the produced site's anonymous data API (private visitor-record
// tables answer [] / null exactly like tables that don't exist — no existence leak); 'owner' = the
// auth-gated content admin, which must keep seeing bookings/orders to run the business.
export type ReadAudience = 'public' | 'owner';

const IDENT = /^[a-z_][a-z0-9_]*$/;            // a legal, safe SQL identifier (no quoting tricks)

// app_<32 hex of the project uuid>. Throws on anything that wouldn't be exactly this — so we can NEVER
// accidentally operate on `public`, an empty name, or an injected identifier.
export function schemaName(projectId: string): string {
  const hex = String(projectId || '').toLowerCase().replace(/[^a-f0-9]/g, '');
  if (hex.length < 16) throw new Error('appdb: refusing — project id too short to namespace: ' + projectId);
  const name = 'app_' + hex.slice(0, 32);
  if (!/^app_[a-f0-9]{16,32}$/.test(name)) throw new Error('appdb: bad schema name ' + name);
  return name;
}

const stripFences = (s: string) => s.replace(/```[a-zA-Z]*\n?/g, '').replace(/```/g, '').trim();
function sqlBody(content: string): string { const s = stripFences(content); const at = s.search(/create\s+table/i); return at >= 0 ? s.slice(at) : s; }

// Strip SQL comments and normalize whitespace (incl. around dots) so the confinement denylist can't be
// fooled by `public /* */ . foo`, `copy\nfrom`, or `set/**/role`. The SANITIZED text is what we both
// validate AND execute, so what passes the check is exactly what runs.
function sanitizeDdl(content: string): string {
  return sqlBody(content)
    .replace(/\/\*[\s\S]*?\*\//g, ' ')   // /* block comments */
    .replace(/--[^\n]*/g, ' ')           // -- line comments
    .replace(/\s+/g, ' ')                // collapse whitespace/newlines
    .replace(/\s*\.\s*/g, '.')           // "public . foo" / "public/**/.foo" -> "public.foo"
    .trim();
}

// Reject any DDL that could escape the project's schema or touch the engine. Generated app DDL never
// legitimately references another schema or session settings — so blocking these is free safety.
function assertConfined(ddl: string) {
  const lower = ddl.toLowerCase();
  // the engine pool is a superuser, so block anything beyond plain tables/indexes/inserts: cross-schema
  // refs, session settings, procedural/privilege/extension constructs, and IO functions.
  for (const bad of ['public.', 'pg_catalog', 'pg_class', 'information_schema', 'search_path', 'set role',
    'set session', 'create schema', 'drop schema', 'drop database', 'alter system', '\\connect', 'dblink',
    'copy ', 'pg_read', 'pg_sleep', 'create extension', 'create or replace', 'create function',
    'create trigger', 'create policy', 'security definer', 'grant ', 'revoke ', 'alter role', 'alter user'])
    if (lower.includes(bad)) throw new Error('appdb: schema DDL contains a disallowed construct: ' + bad.trim());
}

const SENSITIVE = /pass|secret|token|hash|salt|api_?key|private|credential/i;   // never expose these via the public read API

// Provision the project's schema FOR REAL: drop+recreate its isolated namespace and apply the DDL (+ any
// seed INSERTs) inside it. Idempotent — a rebuild re-provisions cleanly. Returns the tables that now exist.
// The agent's DB output -> final DDL: a JSON data-model is COMPILED into perfect, consistent Postgres
// (PKs, FK indexes, types, defaults); raw SQL falls back to the sanitized+confined path (legacy).
export function compileDDL(content: string): { ddl: string; warnings: string[] } {
  const model = parseModel(content);
  if (model) { const c = compile(model); return { ddl: c.ddl, warnings: c.warnings }; }   // generated by us -> trusted
  const ddl = sanitizeDdl(content); assertConfined(ddl); return { ddl, warnings: [] };       // raw SQL -> confine
}

export async function provision(pool: pg.Pool, projectId: string, content: string): Promise<{ schema: string; tables: string[]; migration?: { applied: string[]; skipped: string[] } }> {
  const schema = schemaName(projectId);
  const { ddl } = compileDDL(content);
  if (!/create\s+table/i.test(ddl)) throw new Error('appdb: no tables in the data model / schema output');
  // IDEMPOTENT + non-destructive. A provisioned schema is never re-dropped; on a REBUILD (M3) the
  // new model is MIGRATED onto it: missing tables created (+seeded), missing columns added — rows
  // always survive (a row-count guard rolls the whole migration back if any table loses data).
  const existing = await listTables(pool, projectId);
  if (existing.length) {
    const migration = await migrate(pool, projectId, content, existing);
    return { schema, tables: await listTables(pool, projectId), migration };
  }
  const c = await pool.connect();
  try {
    await c.query('begin');
    await c.query("set local statement_timeout = '15s'");           // bound pathological/runaway DDL
    await c.query(`create schema if not exists "${schema}"`);        // never public; safe under concurrency
    await c.query(`set local search_path to "${schema}"`);           // unqualified CREATE/INSERT land HERE; tx-scoped
    await c.query(ddl);
    await c.query('commit');
  } catch (e) { try { await c.query('rollback'); } catch {} throw e; }
  finally { c.release(); }
  return { schema, tables: await listTables(pool, projectId) };
}

// M3 — SAFE SCHEMA MIGRATION. Diff the new model against the live catalog and apply ONLY additive,
// data-preserving changes: new tables (with their indexes + seeds), new columns (with a sensible
// default so NOT NULL holds on populated tables; relations stay nullable — a guess would be a lie).
// NEVER drops or retypes anything; a type drift is reported and the stored type kept. The whole
// migration runs in ONE transaction with a row-count guard: if any pre-existing table would end up
// with fewer rows, everything rolls back.
const typeDefault = (t: string): string | null =>
  t === 'boolean' ? 'false'
  : /^(integer|numeric)/.test(t) ? '0'
  : t === 'date' || t === 'timestamptz' || /^timestamp/.test(t) ? 'now()'
  : t === 'jsonb' ? `'{}'::jsonb`
  : t === 'text' ? `''`
  : null;
// information_schema data_type -> our compiled type family, for drift comparison
const typeFamily = (t: string): string =>
  /char|text/.test(t) ? 'text' : /^(int|integer|bigint|smallint)/.test(t) ? 'integer'
  : /numeric|decimal|real|double/.test(t) ? 'numeric' : /bool/.test(t) ? 'boolean'
  : /timestamp/.test(t) ? 'timestamptz' : /^date$/.test(t) ? 'date' : /json/.test(t) ? 'jsonb' : t;

export async function migrate(pool: pg.Pool, projectId: string, content: string, existing: string[]): Promise<{ applied: string[]; skipped: string[] }> {
  const schema = schemaName(projectId);
  const model = parseModel(content);
  const applied: string[] = [], skipped: string[] = [];
  if (!model) { skipped.push('raw-SQL model — migration unsupported, existing schema left untouched'); return { applied, skipped }; }
  const { resolved } = compile(model);
  const stmts: string[] = [];
  for (const t of resolved.order) {
    if (!existing.includes(t)) {
      stmts.push(resolved.createSql[t], ...resolved.indexSql[t], ...resolved.seedSql[t]);
      applied.push(`+table "${t}" (${resolved.seedSql[t].length} seed rows)`);
      continue;
    }
    const have = new Map((await typedColumns(pool, schema, t)).map(c => [c.name, c]));
    // FS3: a migrated lifecycle table must not keep a legacy auto-confirm default — new rows are
    // born 'pending' (existing rows untouched; only the default changes).
    if (LIFECYCLE_TABLE.test(t) && have.has('status')) {
      const cur = (await pool.query(`select column_default from information_schema.columns where table_schema=$1 and table_name=$2 and column_name='status'`, [schema, t])).rows[0]?.column_default;
      if (!/pending/.test(String(cur || ''))) {
        stmts.push(`alter table "${t}" alter column "status" set default 'pending';`);
        applied.push(`~"${t}"."status" default -> 'pending' (was ${cur || 'none'} — visitors must never be auto-confirmed)`);
      }
    }
    for (const c of resolved.cols[t]) {
      const cur = have.get(c.name);
      if (cur) {
        if (typeFamily(cur.type) !== typeFamily(c.type)) skipped.push(`~"${t}"."${c.name}": kept ${cur.type} (model wants ${c.type} — retype would risk data)`);
        continue;
      }
      if (c.name === 'status') {
        // FS3: status joins populated lifecycle tables with default 'pending' and NO CHECK (existing
        // rows may carry legacy values a constraint would reject — the closed set is enforced on write)
        stmts.push(`alter table "${t}" add column "status" text not null default 'pending';`);
        applied.push(`+"${t}"."status" (lifecycle, default 'pending')`);
        continue;
      }
      if (c.name === 'ref_token') {
        // FS1: the receipt token joins populated tables NULLABLE with a partial unique index — old
        // rows stay null (an '' backfill would collide on unique and pretend to be findable).
        stmts.push(`alter table "${t}" add column "ref_token" text;`);
        stmts.push(`create unique index if not exists "${t}_ref_token_uq" on "${t}" ("ref_token") where "ref_token" is not null;`);
        applied.push(`+"${t}"."ref_token" (nullable receipt token; pre-existing rows stay null)`);
        continue;
      }
      if (c.ref) {
        // a new relation on a populated table stays NULLABLE — inventing FK values would be a lie
        const refExists = existing.includes(c.ref) || resolved.order.includes(c.ref);
        stmts.push(`alter table "${t}" add column "${c.name}" integer${refExists ? ` references "${c.ref}"(id) on delete set null` : ''};`);
        if (refExists) stmts.push(`create index "${t}_${c.name}_idx" on "${t}" ("${c.name}");`);
        applied.push(`+"${t}"."${c.name}" (relation → ${c.ref}, nullable)`);
        if (c.required) skipped.push(`~"${t}"."${c.name}": required relation added as nullable — existing rows can't be guessed`);
        continue;
      }
      const def = c.def !== undefined ? lit(c.def, c.type) : typeDefault(c.type);
      let sql = `alter table "${t}" add column "${c.name}" ${c.type}`;
      if (def !== null && def !== 'null') sql += ` default ${def}`;
      stmts.push(sql + ';');
      if (c.required && def !== null && def !== 'null') stmts.push(`alter table "${t}" alter column "${c.name}" set not null;`);
      applied.push(`+"${t}"."${c.name}" ${c.type}${def && def !== 'null' ? ` default ${def}` : ''}`);
    }
  }
  if (!stmts.length) return { applied, skipped };
  const before = new Map<string, number>();
  for (const t of existing) before.set(t, Number((await pool.query(`select count(*)::int n from "${schema}"."${t}"`)).rows[0].n));
  const c = await pool.connect();
  try {
    await c.query('begin');
    await c.query("set local statement_timeout = '15s'");
    await c.query(`set local search_path to "${schema}"`);
    for (const s of stmts) await c.query(s);
    for (const [t, n] of before) {
      const now = Number((await c.query(`select count(*)::int n from "${schema}"."${t}"`)).rows[0].n);
      if (now < n) throw new Error(`migration guard: "${t}" would lose rows (${n} → ${now}) — rolled back`);
    }
    await c.query('commit');
  } catch (e) { try { await c.query('rollback'); } catch {} throw e; }
  finally { c.release(); }
  return { applied, skipped };
}

// PQ2 — PLACE ORDER: the checkout write. Deterministic store contract: tables literally named
// products / orders / order_items (enforced by the app_db gate for store briefs). ZERO TRUST in the
// client: prices come from the products table, the total is computed HERE, unit prices are
// snapshotted onto the line items, and the whole write is one transaction.
// the visitor's language for ACTION errors — write paths only (a rejected order/booking is
// exactly the moment a half-English message breaks trust). One tiny indexed query per write.
async function localeOf(pool: pg.Pool, projectId: string): Promise<string | undefined> {
  try { return (await pool.query("select params->>'locale' as l from projects where id=$1", [projectId])).rows[0]?.l || undefined; } catch { return undefined; }
}

export async function placeOrder(pool: pg.Pool, projectId: string, buyer: Record<string, any>, items: { id: any; qty: any; variant?: any }[]): Promise<{ ok: boolean; order?: number; total?: number; ref?: string; error?: string }> {
  const schema = schemaName(projectId);
  const tables = await listTables(pool, projectId);
  for (const t of ['products', 'orders', 'order_items']) if (!tables.includes(t)) return { ok: false, error: 'this site has no store (missing ' + t + ')' };
  const hasVariants = tables.includes('product_variants');   // PQ2 · options — activates the variant path
  // validate items: 1..30 lines, integer ids, qty 1..99, no duplicate product+variant pairs
  if (!Array.isArray(items) || !items.length || items.length > 30) return { ok: false, error: 'cart is empty or too large' };
  const seen = new Set<string>();
  const lines: { id: number; qty: number; variant: number | null }[] = [];
  for (const it of items) {
    const id = Number(it?.id), qty = Number(it?.qty);
    const variant = (hasVariants && it?.variant != null && it?.variant !== '') ? Number(it.variant) : null;
    if (variant !== null && (!Number.isInteger(variant) || variant < 1)) return { ok: false, error: 'invalid cart line' };
    const key = id + ':' + (variant ?? '');
    if (!Number.isInteger(id) || id < 1 || !Number.isInteger(qty) || qty < 1 || qty > 99 || seen.has(key)) return { ok: false, error: 'invalid cart line' };
    seen.add(key); lines.push({ id, qty, variant });
  }
  const name = String(buyer?.customer_name ?? buyer?.name ?? '').trim();
  const email = String(buyer?.email ?? '').trim();
  const loc = await localeOf(pool, projectId);
  if (!name || name.length > 120) return { ok: false, error: L(loc, 'err_name_required') };
  if (!/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(email)) return { ok: false, error: L(loc, 'err_email_required') };
  // server-side pricing — the client\'s numbers are never used
  const allProdCols = await typedColumns(pool, schema, 'products');
  const priceCols = allProdCols.filter(c => /numeric|int|real|double|decimal/.test(c.type) && /^(price|amount|cost)$/.test(c.name));
  if (!priceCols.length) return { ok: false, error: 'products table has no price column' };
  const pcol = priceCols[0].name;
  // PQ2 — stock awareness: which products carry a finite inventory (nullable int column)?
  const hasStock = allProdCols.some(c => c.name === 'stock');
  const ttlCol = ['title', 'name', 'label'].find(n => allProdCols.some(c => c.name === n));
  const prod = await pool.query(`select id, "${pcol}"::numeric as price${ttlCol ? `, "${ttlCol}" as title` : ''} from "${schema}"."products" where id = any($1)`, [lines.map(l => l.id)]);
  const priceById = new Map<number, number>(prod.rows.map((r: any) => [Number(r.id), Number(r.price)]));
  const titleById = new Map<number, string>(prod.rows.map((r: any) => [Number(r.id), String(r.title ?? ('#' + r.id))]));
  for (const l of lines) if (!priceById.has(l.id)) return { ok: false, error: L(loc, 'err_product_gone') };
  // column-flexible write (the model may name columns slightly differently), one transaction
  const oCols = new Set((await typedColumns(pool, schema, 'orders')).map(c => c.name));
  const iCols = new Set((await typedColumns(pool, schema, 'order_items')).map(c => c.name));
  const nameCol = ['customer_name', 'name', 'buyer_name'].find(c => oCols.has(c));
  const qtyCol = ['qty', 'quantity'].find(c => iCols.has(c));
  const unitCol = ['unit_price', 'price'].find(c => iCols.has(c));
  const prodCol = ['product_id'].find(c => iCols.has(c));
  const orderCol = ['order_id'].find(c => iCols.has(c));
  if (!nameCol || !qtyCol || !prodCol || !orderCol) return { ok: false, error: 'store schema is missing standard order columns' };
  const vCols = hasVariants ? (await typedColumns(pool, schema, 'product_variants')).map(x => x.name) : [];
  const vHasPrice = vCols.includes('price'), vHasStock = vCols.includes('stock'), vHasName = vCols.includes('name');
  const c = await pool.connect();
  try {
    await c.query('begin');
    await c.query("set local statement_timeout = '10s'");
    // PQ2 · VARIANTS: resolve each line's variant INSIDE the transaction (locked) — the variant must
    // belong to the product; its price (when set) overrides; its stock (when tracked) is the guard.
    // A product that HAS options may not be bought without choosing one — same rule as a real shop.
    const effPrice = new Map<string, number>();
    const vnameByKey = new Map<string, string>();
    for (const l of lines) {
      const key = l.id + ':' + (l.variant ?? '');
      const ttl = titleById.get(l.id) || ('#' + l.id);
      if (l.variant !== null) {
        const vr = (await c.query(`select ${vHasName ? '"name", ' : ''}${vHasPrice ? '"price"::numeric as price, ' : ''}${vHasStock ? '"stock", ' : ''}"product_id" from "${schema}"."product_variants" where id=$1 for update`, [l.variant])).rows[0];
        if (!vr || Number(vr.product_id) !== l.id) { await c.query('rollback'); return { ok: false, error: L(loc, 'err_option_gone') }; }
        const vname = vHasName ? String(vr.name ?? '') : '';
        if (vHasStock && vr.stock != null) {
          const stk = Number(vr.stock);
          if (l.qty > stk) { await c.query('rollback'); return { ok: false, error: stk === 0 ? L(loc, 'err_sold_out_item', { t: `${ttl} — ${vname}` }) : L(loc, 'err_only_n_of', { n: stk, t: `${ttl} — ${vname}` }) }; }
        }
        effPrice.set(key, vHasPrice && vr.price != null ? Number(vr.price) : priceById.get(l.id)!);
        vnameByKey.set(key, vname);
      } else {
        if (hasVariants) {
          const n = Number((await c.query(`select count(*)::int n from "${schema}"."product_variants" where product_id=$1`, [l.id])).rows[0].n);
          if (n > 0) { await c.query('rollback'); return { ok: false, error: L(loc, 'err_has_options', { t: ttl }) }; }
        }
        effPrice.set(key, priceById.get(l.id)!);
      }
    }
    const total = Math.round(lines.reduce((s2, l) => s2 + effPrice.get(l.id + ':' + (l.variant ?? ''))! * l.qty, 0) * 100) / 100;
    // lock each tracked row and validate before any write — the whole order rolls back atomically on reject
    if (hasStock) {
      for (const l of lines) {
        if (l.variant !== null) continue;   // variant lines guard stock on the VARIANT row above
        const srow = (await c.query(`select ${ttlCol ? `"${ttlCol}" as title, ` : ''}stock from "${schema}"."products" where id=$1 for update`, [l.id])).rows[0];
        if (srow && srow.stock != null) {
          const stk = Number(srow.stock);
          const ttl = ttlCol ? String(srow.title ?? ('#' + l.id)) : ('#' + l.id);
          if (l.qty > stk) { await c.query('rollback'); return { ok: false, error: stk === 0 ? L(loc, 'err_sold_out_item', { t: ttl }) : L(loc, 'err_only_n_of', { n: stk, t: ttl }) }; }
        }
      }
    }
    const cols: string[] = [nameCol]; const vals: any[] = [name];
    // FS1 — the buyer keeps a receipt too: mint the same secret token every visitor action gets
    const ref = oCols.has('ref_token') ? randomBytes(16).toString('hex') : undefined;
    if (ref) { cols.push('ref_token'); vals.push(ref); }
    if (oCols.has('email')) { cols.push('email'); vals.push(email); }
    if (oCols.has('phone') && buyer?.phone) { cols.push('phone'); vals.push(String(buyer.phone).slice(0, 40)); }
    if (oCols.has('notes') && buyer?.notes) { cols.push('notes'); vals.push(String(buyer.notes).slice(0, 500)); }
    if (oCols.has('status')) { cols.push('status'); vals.push('new'); }
    if (oCols.has('total')) { cols.push('total'); vals.push(total); }
    const o = await c.query(`insert into "${schema}"."orders" (${cols.map(x => `"${x}"`).join(',')}) values (${cols.map((_, i) => '$' + (i + 1)).join(',')}) returning id`, vals);
    const orderId = Number(o.rows[0].id);
    for (const l of lines) {
      const key = l.id + ':' + (l.variant ?? '');
      const ic: string[] = [orderCol, prodCol, qtyCol]; const iv: any[] = [orderId, l.id, l.qty];
      if (unitCol) { ic.push(unitCol); iv.push(effPrice.get(key)); }
      // variant SNAPSHOT on the line — the receipt reads "Tee — XL" even if the option changes later
      if (l.variant !== null && iCols.has('variant_id')) { ic.push('variant_id'); iv.push(l.variant); }
      if (l.variant !== null && iCols.has('variant_name') && vnameByKey.get(key)) { ic.push('variant_name'); iv.push(vnameByKey.get(key)); }
      await c.query(`insert into "${schema}"."order_items" (${ic.map(x => `"${x}"`).join(',')}) values (${ic.map((_, i) => '$' + (i + 1)).join(',')})`, iv);
    }
    if (hasStock) {
      for (const l of lines) { if (l.variant === null) await c.query(`update "${schema}"."products" set stock = stock - $1 where id=$2 and stock is not null`, [l.qty, l.id]); }
    }
    if (vHasStock) {
      for (const l of lines) { if (l.variant !== null) await c.query(`update "${schema}"."product_variants" set stock = stock - $1 where id=$2 and stock is not null`, [l.qty, l.variant]); }
    }
    await c.query('commit');
    return { ok: true, order: orderId, total, ref };
  } catch (e: any) {
    try { await c.query('rollback'); } catch {}
    console.error('placeOrder', projectId, e?.message ?? e);
    return { ok: false, error: 'could not place the order — please try again' };
  } finally { c.release(); }
}

// PQ2 · VARIANTS — one product's options for the PDP picker (public data: name, price, stock).
export async function productVariants(pool: pg.Pool, projectId: string, productId: number): Promise<{ id: number; name: string; price: number | null; stock: number | null }[]> {
  const schema = schemaName(projectId);
  if (!Number.isInteger(productId) || !(await listTables(pool, projectId)).includes('product_variants')) return [];
  const cols = (await typedColumns(pool, schema, 'product_variants')).map(c => c.name);
  if (!cols.includes('product_id')) return [];
  const sel = ['id', cols.includes('name') ? '"name"' : `'Option ' || id as name`, cols.includes('price') ? '"price"::numeric as price' : 'null as price', cols.includes('stock') ? '"stock"' : 'null as stock'];
  const r = await pool.query(`select ${sel.join(', ')} from "${schema}"."product_variants" where product_id=$1 order by id limit 24`, [productId]);
  return r.rows.map((v: any) => ({ id: Number(v.id), name: String(v.name ?? ''), price: v.price != null ? Number(v.price) : null, stock: v.stock != null ? Number(v.stock) : null }));
}

export async function listTables(pool: pg.Pool, projectId: string): Promise<string[]> {
  const schema = schemaName(projectId);
  const r = await pool.query(
    "select table_name from information_schema.tables where table_schema=$1 and table_type='BASE TABLE' order by table_name", [schema]);
  return r.rows.map((x: any) => x.table_name);
}

async function typedColumns(pool: pg.Pool, schema: string, table: string): Promise<{ name: string; type: string; nullable: boolean }[]> {
  const r = await pool.query('select column_name, data_type, is_nullable from information_schema.columns where table_schema=$1 and table_name=$2 order by ordinal_position', [schema, table]);
  return r.rows.map((x: any) => ({ name: x.column_name, type: x.data_type, nullable: x.is_nullable === 'YES' }));
}
// coerce a posted string to the column's real type (so a numeric/boolean column stores correctly)
function coerce(v: any, type: string): any {
  if (v === '' || v === null || v === undefined) return null;
  if (/bool/.test(type)) return v === true || /^(true|on|1|yes)$/i.test(String(v));
  if (/int|numeric|real|double|decimal/.test(type)) { const n = Number(v); return Number.isFinite(n) ? n : null; }
  return String(v);
}

// pick a human display column for a table: name/title/label, else the first text column, else id
async function displayColumn(pool: pg.Pool, schema: string, table: string): Promise<string> {
  const cols = await typedColumns(pool, schema, table);
  const pref = cols.find(c => ['name', 'title', 'label'].includes(c.name));
  if (pref) return pref.name;
  const txt = cols.find(c => /char|text/.test(c.type) && c.name !== 'id');
  return txt ? txt.name : 'id';
}

// Row decoration shared by the LIST read (cards) and the SINGLE read (product detail page) — ONE
// source of truth, so a detail page always shows exactly what its card shows, plus the rest.
// RELATION-AWARE: each FK column (x_id -> table y) is resolved to y's display value and exposed as `x`,
// so it shows "Category: Ceramics", not "category_id: 3". Secrets are stripped.
async function decorateRows(pool: pg.Pool, projectId: string, schema: string, table: string, tables: string[], rows: any[], audience: ReadAudience = 'public'): Promise<any[]> {
  try {
    const fks = (await pool.query(
      `select kcu.column_name as col, ccu.table_name as ref
       from information_schema.table_constraints tc
       join information_schema.key_column_usage kcu on kcu.constraint_name=tc.constraint_name and kcu.table_schema=tc.table_schema
       join information_schema.constraint_column_usage ccu on ccu.constraint_name=tc.constraint_name and ccu.table_schema=tc.table_schema
       where tc.constraint_type='FOREIGN KEY' and tc.table_schema=$1 and tc.table_name=$2`, [schema, table])).rows;
    for (const fk of fks) {
      if (!IDENT.test(fk.col) || !IDENT.test(fk.ref) || !tables.includes(fk.ref)) continue;
      const ids = [...new Set(rows.map((r: any) => r[fk.col]).filter((v: any) => v != null))];
      if (!ids.length) continue;
      const dcol = await displayColumn(pool, schema, fk.ref);
      if (!IDENT.test(dcol)) continue;
      const map = new Map((await pool.query(`select id, "${dcol}" as d from "${schema}"."${fk.ref}" where id = any($1)`, [ids])).rows.map((r: any) => [r.id, r.d]));
      const label = fk.col.replace(/_id$/, '');
      // the OWNER keeps the raw id too — the edit form needs the current relation, not just its label
      for (const r of rows) { r[label] = map.get(r[fk.col]) ?? null; if (audience !== 'owner') delete r[fk.col]; }
    }
  } catch {}
  return rows.map((row: any) => {
    const o = { ...row }; for (const k of Object.keys(o)) if (SENSITIVE.test(k)) delete o[k];
    // agency-grade cards: attach the row's cached local photo when one exists and no real image column
    // is already populated (deterministic file lookup, no network — see rowmedia.ts).
    const img = localRowImage(projectId, table, o); if (img) o._image = img;
    return o;
  });
}

// Read rows from a REAL project table (validated against the schema's own catalog; never arbitrary SQL).
export async function readRows(pool: pg.Pool, projectId: string, table: string, limit = 50, audience: ReadAudience = 'public'): Promise<any[]> {
  const schema = schemaName(projectId);
  if (!IDENT.test(table)) return [];
  if (audience !== 'owner' && PRIVATE_READ.test(table)) return [];   // FS0: visitor records are never publicly listable
  const tables = await listTables(pool, projectId);
  if (!tables.includes(table)) return [];
  const lim = Math.max(1, Math.min(200, Number(limit) || 50));
  const rows = (await pool.query(`select * from "${schema}"."${table}" order by id desc limit ${lim}`)).rows;
  // PQ2 · variants: product cards need to know they have options — the grid then offers
  // "Choose options" (to the PDP) instead of a bare Add-to-cart the server would refuse
  if (table === 'products' && tables.includes('product_variants')) {
    try {
      const vc = (await pool.query(`select product_id, count(*)::int n from "${schema}"."product_variants" group by product_id`)).rows;
      const byId = new Map(vc.map((v: any) => [Number(v.product_id), Number(v.n)]));
      for (const r of rows) if (byId.has(Number(r.id))) (r as any)._variants = byId.get(Number(r.id));
    } catch {}
  }
  return decorateRows(pool, projectId, schema, table, tables, rows, audience);
}

// FS1 — THE scoped read: ONE column, ONE value, parameterized, identifier-validated, decorated like
// every other read. The only public way into a private table is its secret ref_token (the receipt) —
// long enough to be unguessable, unique by index, stripped from every row the API returns (the
// caller already holds it, from their own URL). Everything downstream (receipts, find-my-booking,
// later my-bookings) composes over this single primitive.
export async function readScoped(pool: pg.Pool, projectId: string, table: string, col: string, value: string, limit = 20): Promise<any[]> {
  const schema = schemaName(projectId);
  if (!IDENT.test(table) || !IDENT.test(col)) return [];
  if (PRIVATE_READ.test(table) && (col !== 'ref_token' || String(value || '').length < 16)) return [];
  const tables = await listTables(pool, projectId);
  if (!tables.includes(table)) return [];
  if (!(await typedColumns(pool, schema, table)).some(c => c.name === col)) return [];
  const lim = Math.max(1, Math.min(50, Number(limit) || 20));
  const rows = (await pool.query(`select * from "${schema}"."${table}" where "${col}"=$1 order by id desc limit ${lim}`, [String(value)])).rows;
  return decorateRows(pool, projectId, schema, table, tables, rows);
}

// FS1 — resolve a receipt token to its table without knowing which private table it lives in
// (find-my-booking pastes just the code). Bounded: only private tables that carry a ref_token column.
export async function findByToken(pool: pg.Pool, projectId: string, token: string): Promise<{ table: string; row: any } | null> {
  if (String(token || '').length < 16 || !/^[0-9a-f]{16,64}$/i.test(String(token))) return null;
  const schema = schemaName(projectId);
  for (const t of await listTables(pool, projectId)) {
    if (!PRIVATE_READ.test(t)) continue;
    if (!(await typedColumns(pool, schema, t)).some(c => c.name === 'ref_token')) continue;
    const rows = await readScoped(pool, projectId, t, 'ref_token', token, 1);
    if (rows.length) return { table: t, row: rows[0] };
  }
  return null;
}

// FS3 — internal: a row's contact address + receipt token, for lifecycle notifications ("your
// booking is confirmed"). Never exposed through any public API.
export async function rowContact(pool: pg.Pool, projectId: string, table: string, id: number): Promise<{ email: string; ref: string | null } | null> {
  const schema = schemaName(projectId);
  if (!IDENT.test(table) || !Number.isInteger(id)) return null;
  if (!(await listTables(pool, projectId)).includes(table)) return null;
  const cols = (await typedColumns(pool, schema, table)).map(c => c.name);
  const emailCol = ['email', 'customer_email', 'visitor_email', 'contact_email'].find(c => cols.includes(c));
  if (!emailCol) return null;
  const r = (await pool.query(`select "${emailCol}" as email${cols.includes('ref_token') ? ', "ref_token"' : ''} from "${schema}"."${table}" where id=$1`, [id])).rows[0];
  if (!r || !/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(String(r.email || ''))) return null;
  return { email: String(r.email), ref: (r as any).ref_token || null };
}

// FS1 — the MAILED lookup: every receipt link for an email address across private tables. Server-
// internal ONLY: the route mails the result and always answers "sent" — the API never returns it,
// so there is no public enumeration path.
export async function receiptLinksByEmail(pool: pg.Pool, projectId: string, email: string): Promise<{ table: string; ref: string }[]> {
  const schema = schemaName(projectId); const out: { table: string; ref: string }[] = [];
  const em = String(email || '').trim().toLowerCase();
  if (!/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(em)) return out;
  for (const t of await listTables(pool, projectId)) {
    if (!PRIVATE_READ.test(t)) continue;
    const cols = await typedColumns(pool, schema, t);
    if (!cols.some(c => c.name === 'ref_token') || !cols.some(c => c.name === 'email')) continue;
    const rows = (await pool.query(`select ref_token from "${schema}"."${t}" where lower(email)=$1 and ref_token is not null order by id desc limit 10`, [em])).rows;
    for (const r of rows) out.push({ table: t, ref: r.ref_token });
  }
  return out;
}

// PDP — ONE record by id, decorated exactly like the list read (relations resolved, secrets stripped,
// cached photo attached). null when the table or row doesn't exist — the caller answers 404 honestly.
export async function readRow(pool: pg.Pool, projectId: string, table: string, id: number, audience: ReadAudience = 'public'): Promise<any | null> {
  const schema = schemaName(projectId);
  if (!IDENT.test(table) || !Number.isInteger(id) || id < 1 || id > 2147483647) return null;   // int4-bounded — a huge URL id is a 404, never a thrown query
  if (audience !== 'owner' && PRIVATE_READ.test(table)) return null;   // FS0: a visitor record is not publicly addressable by id
  const tables = await listTables(pool, projectId);
  if (!tables.includes(table)) return null;
  const rows = (await pool.query(`select * from "${schema}"."${table}" where id=$1`, [id])).rows;
  if (!rows.length) return null;
  return (await decorateRows(pool, projectId, schema, table, tables, rows, audience))[0];
}

// FS0 — SYSTEM-OWNED columns: lifecycle state belongs to the system/owner, never to the visitor
// (a public booking form must not offer "Status", and a crafted POST must not set it either).
const SYSTEM_COLS = /^(status|state|approved|confirmed|verified)$/i;

// Insert one row into a REAL project table — only existing columns, type-coerced, fully parameterized.
// FS1: on a private (visitor-record) table with a ref_token column, a 128-bit receipt token is
// generated HERE (never client-supplied — SENSITIVE already blocks it from `data`) and returned so
// the visitor can be shown their receipt. Returns { ok, ref? }.
export async function insertRow(pool: pg.Pool, projectId: string, table: string, data: Record<string, any>, audience: ReadAudience = 'public'): Promise<{ ok: boolean; ref?: string; error?: string }> {
  const schema = schemaName(projectId);
  if (!IDENT.test(table)) return { ok: false };
  if (!(await listTables(pool, projectId)).includes(table)) return { ok: false };
  const cols = await typedColumns(pool, schema, table);
  const use = cols.filter(c => IDENT.test(c.name) && c.name in (data || {}) && !['id', 'created_at'].includes(c.name) && !SENSITIVE.test(c.name) && (audience === 'owner' || !SYSTEM_COLS.test(c.name)));
  if (!use.length) return { ok: false };
  // FS3 — booking semantics validated SERVER-side, with errors a visitor can act on (never a silent
  // lie in the copy): a date in the past is refused; a full slot is refused (capacity-aware).
  if (audience !== 'owner' && PRIVATE_READ.test(table)) {
    const today = new Date().toISOString().slice(0, 10);
    for (const c of use) {
      if (!/^(date|timestamp)/.test(c.type)) continue;
      const m = String(data[c.name] ?? '').match(/^(\d{4}-\d{2}-\d{2})/);
      if (m && m[1] < today) { const l2 = await localeOf(pool, projectId); return { ok: false, error: L(l2, 'err_past_date', { f: columnLabel(l2, c.name, c.name.replace(/_/g, ' ')).toLowerCase() }) }; }
    }
    if (SLOT_TABLE.test(table)) {
      const slotErr = await slotGuard(pool, projectId, schema, table, cols, data);
      if (slotErr) return { ok: false, error: slotErr };
    }
  }
  const names = use.map(c => `"${c.name}"`); const vals: any[] = use.map(c => coerce(data[c.name], c.type));
  let ref: string | undefined;
  if (PRIVATE_READ.test(table) && cols.some(c => c.name === 'ref_token')) {
    ref = randomBytes(16).toString('hex');
    names.push('"ref_token"'); vals.push(ref);
  }
  try {
    await pool.query(`insert into "${schema}"."${table}" (${names.join(',')}) values (${vals.map((_, i) => '$' + (i + 1)).join(',')})`, vals);
  } catch (e: any) {
    if (e?.code === '23505') return { ok: false, error: L(await localeOf(pool, projectId), 'err_slot_taken') };   // unique race
    throw e;
  }
  return { ok: true, ref };
}

// FS3 — the SLOT GUARD: double-booking is refused by the SERVER, never promised by copy. The slot's
// coordinates are the booked resource FKs (never the customer-ish ones) plus the date/time columns
// actually submitted; a slot holds ONE booking unless the booked resource row declares a `capacity`
// (a class with 12 spots books 12 times). Cancelled/declined rows free their slot.
async function slotGuard(pool: pg.Pool, projectId: string, schema: string, table: string, cols: { name: string; type: string }[], data: Record<string, any>): Promise<string | null> {
  const coord = cols.filter(c =>
    (c.name.endsWith('_id') && !/customer|client|user|visitor|member|guest/.test(c.name)) ||
    (/^(date|timestamp|time)/.test(c.type) && c.name !== 'created_at'));
  const used = coord.filter(c => data[c.name] !== undefined && data[c.name] !== null && data[c.name] !== '');
  if (used.length < 2 || !used.some(c => /^(date|timestamp|time)/.test(c.type))) return null;   // not slot-shaped — never wrongly forced
  const hasStatus = cols.some(c => c.name === 'status');
  const where = used.map((c, i) => `"${c.name}"=$${i + 1}`).join(' and ');
  const taken = Number((await pool.query(
    `select count(*)::int n from "${schema}"."${table}" where ${where}${hasStatus ? ` and coalesce("status",'pending') not in ('declined','cancelled')` : ''}`,
    used.map(c => coerce(data[c.name], c.type)))).rows[0].n);
  // capacity: the first booked-resource row that declares one
  let capacity = 1;
  try {
    const fks = (await pool.query(
      `select kcu.column_name as col, ccu.table_name as ref
       from information_schema.table_constraints tc
       join information_schema.key_column_usage kcu on kcu.constraint_name=tc.constraint_name and kcu.table_schema=tc.table_schema
       join information_schema.constraint_column_usage ccu on ccu.constraint_name=tc.constraint_name and ccu.table_schema=tc.table_schema
       where tc.constraint_type='FOREIGN KEY' and tc.table_schema=$1 and tc.table_name=$2`, [schema, table])).rows;
    for (const fk of fks) {
      if (!used.some(c => c.name === fk.col) || !IDENT.test(fk.ref)) continue;
      const refCols = (await typedColumns(pool, schema, fk.ref)).map(c => c.name);
      if (!refCols.includes('capacity')) continue;
      const cap = Number((await pool.query(`select "capacity" from "${schema}"."${fk.ref}" where id=$1`, [coerce(data[fk.col], 'integer')])).rows[0]?.capacity);
      if (Number.isInteger(cap) && cap > 0) { capacity = cap; break; }
    }
  } catch {}
  if (taken >= capacity) { const gl = await localeOf(pool, projectId); return capacity > 1 ? L(gl, 'err_slot_full') : L(gl, 'err_slot_taken'); }
  return null;
}

// FS5 — REAL AVAILABILITY: the free slots for a booking day, computed by the SERVER from the same
// coordinates the slot guard enforces (resource FKs + the timestamp column; cancelled/declined rows
// free their slot; a resource's `capacity` books N times). This is the READ the guard always implied:
// instead of guessing a time and being refused, the visitor picks from what is actually open.
// Reveals ONLY aggregate availability — never who booked. Deterministic hourly grid 09:00–16:00.
export async function freeSlots(pool: pg.Pool, projectId: string, table: string, date: string, refs: Record<string, any> = {}): Promise<{ t: string; free: boolean }[] | null> {
  const schema = schemaName(projectId);
  if (!SLOT_TABLE.test(table) || !IDENT.test(table) || !/^\d{4}-\d{2}-\d{2}$/.test(String(date))) return null;
  if (!(await listTables(pool, projectId)).includes(table)) return null;
  const cols = await typedColumns(pool, schema, table);
  const ts = cols.find(c => /^(timestamp|date)/.test(c.type) && c.name !== 'created_at');
  if (!ts) return null;
  // resource coordinates: only real non-customer *_id columns, numeric values — anything else ignored
  const refCols = cols.filter(c => c.name.endsWith('_id') && !/customer|client|user|visitor|member|guest/.test(c.name)).map(c => c.name);
  const conds: string[] = []; const args: any[] = [];
  const usedRefs: Record<string, number> = {};
  for (const [k, v] of Object.entries(refs || {})) {
    const n = Number(v);
    if (!refCols.includes(k) || !Number.isInteger(n)) continue;
    args.push(n); conds.push(`"${k}"=$${args.length}`); usedRefs[k] = n;
  }
  const hasStatus = cols.some(c => c.name === 'status');
  args.push(date);
  const taken = (await pool.query(
    `select to_char("${ts.name}", 'HH24:MI') as t, count(*)::int n from "${schema}"."${table}"
     where "${ts.name}"::date = $${args.length}${conds.length ? ' and ' + conds.join(' and ') : ''}${hasStatus ? ` and coalesce("status",'pending') not in ('declined','cancelled')` : ''}
     group by 1`, args)).rows;
  // capacity: the first provided resource whose table declares one (mirrors slotGuard exactly)
  let capacity = 1;
  try {
    const fks = (await pool.query(
      `select kcu.column_name as col, ccu.table_name as ref
       from information_schema.table_constraints tc
       join information_schema.key_column_usage kcu on kcu.constraint_name=tc.constraint_name and kcu.table_schema=tc.table_schema
       join information_schema.constraint_column_usage ccu on ccu.constraint_name=tc.constraint_name and ccu.table_schema=tc.table_schema
       where tc.constraint_type='FOREIGN KEY' and tc.table_schema=$1 and tc.table_name=$2`, [schema, table])).rows;
    for (const fk of fks) {
      if (!(fk.col in usedRefs) || !IDENT.test(fk.ref)) continue;
      const refCols2 = (await typedColumns(pool, schema, fk.ref)).map(c => c.name);
      if (!refCols2.includes('capacity')) continue;
      const cap = Number((await pool.query(`select "capacity" from "${schema}"."${fk.ref}" where id=$1`, [usedRefs[fk.col]])).rows[0]?.capacity);
      if (Number.isInteger(cap) && cap > 0) { capacity = cap; break; }
    }
  } catch {}
  // the business grid: from the model's OWN opening-hours table when it ships one (the machine-table
  // exclusion keeps it off catalogs; here it becomes useful); else the deterministic 09:00–17:00.
  // Numeric weekdays read as 0/7=Sunday…6=Saturday; names are preferred and unambiguous.
  let openH = 9, closeH = 17;
  const hoursTable = (await listTables(pool, projectId)).find(t => /^(opening_?hours?|business_?hours?|store_?hours?|hours)$/i.test(t));
  if (hoursTable) {
    const hc = (await typedColumns(pool, schema, hoursTable)).map(c => c.name);
    const dayCol = hc.find(c => /^(day|weekday|day_of_week|dow|day_name)$/.test(c));
    const openCol = hc.find(c => /open/.test(c) && c !== dayCol);
    const closeCol = hc.find(c => /clos/.test(c));
    if (dayCol && openCol && closeCol) {
      const DAYNUM: Record<string, number> = { sunday: 0, sun: 0, monday: 1, mon: 1, tuesday: 2, tue: 2, tues: 2, wednesday: 3, wed: 3, thursday: 4, thu: 4, thur: 4, thurs: 4, friday: 5, fri: 5, saturday: 6, sat: 6 };
      const ph = (v: any): number | null => { const m = String(v ?? '').trim().match(/^(\d{1,2})(?::\d{2})?(?::\d{2})?\s*(am|pm)?$/i); if (!m) return null; let h2 = Number(m[1]) % 24; const ap = (m[2] || '').toLowerCase(); if (ap === 'pm' && h2 < 12) h2 += 12; if (ap === 'am' && h2 === 12) h2 = 0; return h2; };
      try {
        const rows2 = (await pool.query(`select "${dayCol}"::text as d, "${openCol}"::text as o, "${closeCol}"::text as c from "${schema}"."${hoursTable}" limit 14`)).rows;
        const wd = new Date(date + 'T12:00:00').getDay();
        const hit = rows2.find((r: any) => { const dv = String(r.d ?? '').trim().toLowerCase(); const n = /^\d+$/.test(dv) ? (Number(dv) % 7) : DAYNUM[dv]; return n === wd; });
        if (!hit) return [];   // closed that day — no slots is the honest answer
        const o = ph(hit.o), c2 = ph(hit.c);
        if (o !== null && c2 !== null && c2 > o) { openH = o; closeH = c2; }
      } catch {}
    }
  }
  const now = Date.now();
  const out: { t: string; free: boolean }[] = [];
  for (let h = openH; h < closeH; h++) {
    const t = String(h).padStart(2, '0') + ':00';
    const n = Number(taken.find((r: any) => r.t === t)?.n || 0);
    out.push({ t, free: new Date(`${date}T${t}:00`).getTime() > now && n < capacity });
  }
  return out;
}

// IMAGE UPLOAD — the owner sets their OWN photo on a content row (PQ3's listed gap). The file type
// comes from MAGIC BYTES, never the filename; size-capped; stored under the site's own assets; the
// row's image column is updated to the served path so the live site shows it on the next load.
const UPLOAD_SITES = new URL('../sites/', import.meta.url);
const IMG_COL = /image|photo|picture|cover|thumb|banner|avatar|logo/i;
function sniffImage(buf: Buffer): string | null {
  if (buf.length > 3 && buf[0] === 0xff && buf[1] === 0xd8 && buf[2] === 0xff) return 'jpg';
  if (buf.length > 7 && buf.readUInt32BE(0) === 0x89504e47) return 'png';
  if (buf.length > 11 && buf.toString('ascii', 0, 4) === 'RIFF' && buf.toString('ascii', 8, 12) === 'WEBP') return 'webp';
  if (buf.length > 5 && buf.toString('ascii', 0, 4) === 'GIF8') return 'gif';
  return null;
}
export async function saveRowImage(pool: pg.Pool, projectId: string, table: string, rid: number, b64: string): Promise<{ ok: true; path: string } | { ok: false; error: string }> {
  const schema = schemaName(projectId);
  if (!IDENT.test(table) || /^_relay_/.test(table) || !Number.isInteger(rid) || rid < 1) return { ok: false, error: 'bad request' };
  if (!(await listTables(pool, projectId)).includes(table)) return { ok: false, error: 'unknown collection' };
  const cols = await typedColumns(pool, schema, table);
  const imgCol = cols.find(c => IMG_COL.test(c.name) && /text|char/.test(c.type) && !SENSITIVE.test(c.name));
  if (!imgCol) return { ok: false, error: 'this collection has no image field' };
  const row = (await pool.query(`select id from "${schema}"."${table}" where id=$1`, [rid])).rows[0];
  if (!row) return { ok: false, error: 'record not found' };
  const clean = String(b64 || '').replace(/^data:[^,]*,/, '');
  if (clean.length > 4_200_000) return { ok: false, error: 'image too large (max 3 MB)' };
  let buf: Buffer;
  try { buf = Buffer.from(clean, 'base64'); } catch { return { ok: false, error: 'not a valid image' }; }
  const iloc = await localeOf(pool, projectId);
  if (buf.length < 24 || buf.length > 3_000_000) return { ok: false, error: buf.length <= 24 ? L(iloc, 'err_not_image') : L(iloc, 'err_image_big') };
  const ext = sniffImage(buf);
  if (!ext) return { ok: false, error: L(iloc, 'err_bad_filetype') };
  const { mkdirSync, writeFileSync } = await import('node:fs');
  const { fileURLToPath } = await import('node:url');
  const rel = `assets/up-${randomBytes(6).toString('hex')}.${ext}`;
  const dir = new URL(projectId + '/', UPLOAD_SITES);
  mkdirSync(fileURLToPath(new URL('assets/', dir)), { recursive: true });
  writeFileSync(fileURLToPath(new URL(rel, dir)), buf);
  const served = `/sites/${projectId}/${rel}`;
  await pool.query(`update "${schema}"."${table}" set "${imgCol.name}"=$1 where id=$2`, [served, rid]);
  return { ok: true, path: served };
}

// CSV EXPORT — the owner downloads their records ("your data is yours"; the accountant wants the
// orders). Owner audience (private tables included), sensitive columns stripped, RFC-quoted, BOM
// for Excel, and formula-injection guarded (a value starting =/+/-/@ gets a leading apostrophe).
export async function exportCsv(pool: pg.Pool, projectId: string, table: string): Promise<string | null> {
  const schema = schemaName(projectId);
  if (!IDENT.test(table) || /^_relay_/.test(table) || !(await listTables(pool, projectId)).includes(table)) return null;
  const cols = (await typedColumns(pool, schema, table)).map(c => c.name).filter(c => !SENSITIVE.test(c));
  if (!cols.length) return null;
  const rows = (await pool.query(`select ${cols.map(c => `"${c}"`).join(', ')} from "${schema}"."${table}" order by id limit 5000`)).rows;
  const cell = (v: any): string => {
    if (v === null || v === undefined) return '';
    let s2 = v instanceof Date ? v.toISOString() : String(v);
    if (/^[=+\-@]/.test(s2)) s2 = "'" + s2;                      // CSV formula injection guard
    return /[",\n\r]/.test(s2) ? '"' + s2.replace(/"/g, '""') + '"' : s2;
  };
  const lines = [cols.join(','), ...rows.map((r: any) => cols.map(c => cell(r[c])).join(','))];
  return '\ufeff' + lines.join('\r\n') + '\r\n';
}

// PQ3 — CLIENT CONTENT EDITING. Directus lives in a SEPARATE database and cannot reach the app_<hex>
// schema (that's where products/menu/posts really live), so the owner edits their content through
// Relay's own owner-scoped admin over THIS API. The live site already reads these tables live, so an
// edit shows immediately. Same safety contract as insert/read: namespace-confined, identifier-checked,
// parameterized, type-coerced, secret columns never touched.

// System tables the client should NOT hand-edit as "content": join/system/transactional tables and
// anything with no human-meaningful display column. Everything else (products, menu, posts, team…) is
// editable content the client owns.
const CONTENT_HIDDEN = /^(_relay_\w+|order_items|orders|submissions|sessions|auth|tokens?|migrations?|users?|accounts?)$/i;

// The editable content collections of a site — the "Products / Menu / Posts" a client manages.
export async function contentTables(pool: pg.Pool, projectId: string): Promise<{ table: string; label: string; rows: number; display: string }[]> {
  const schema = schemaName(projectId);
  const out: { table: string; label: string; rows: number; display: string }[] = [];
  for (const t of await listTables(pool, projectId)) {
    if (CONTENT_HIDDEN.test(t)) continue;
    const disp = await displayColumn(pool, schema, t);
    if (disp === 'id') continue;   // no human handle -> not client-facing content
    let rows = 0; try { rows = Number((await pool.query(`select count(*)::int n from "${schema}"."${t}"`)).rows[0].n); } catch {}
    out.push({ table: t, label: t.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase()), rows, display: disp });
  }
  return out;
}

// One record by id (secret columns stripped) — for the edit form.
export async function getRow(pool: pg.Pool, projectId: string, table: string, id: number): Promise<any | null> {
  const schema = schemaName(projectId);
  if (!IDENT.test(table) || !Number.isInteger(id) || !(await listTables(pool, projectId)).includes(table)) return null;
  const r = (await pool.query(`select * from "${schema}"."${table}" where id=$1`, [id])).rows[0];
  if (!r) return null;
  const o = { ...r }; for (const k of Object.keys(o)) if (SENSITIVE.test(k)) delete o[k];
  return o;
}

// UPDATE a record — only real, non-system columns the caller supplied; type-coerced; id/created_at and
// secret columns can never be written. Returns false if the table/row/columns don't validate.
export async function updateRow(pool: pg.Pool, projectId: string, table: string, id: number, data: Record<string, any>): Promise<boolean> {
  const schema = schemaName(projectId);
  if (!IDENT.test(table) || !Number.isInteger(id) || !(await listTables(pool, projectId)).includes(table)) return false;
  // FS3: the lifecycle status only ever moves within the closed set — even for the owner
  if (data && 'status' in data && LIFECYCLE_TABLE.test(table)) {
    const v = String(data.status ?? '').toLowerCase().trim();
    if (!STATUS_SET.includes(v)) return false;
    data = { ...data, status: v };
  }
  const use = (await typedColumns(pool, schema, table)).filter(c => IDENT.test(c.name) && c.name in (data || {}) && !['id', 'created_at'].includes(c.name) && !SENSITIVE.test(c.name));
  if (!use.length) return false;
  const set = use.map((c, i) => `"${c.name}"=$${i + 1}`).join(',');
  const r = await pool.query(`update "${schema}"."${table}" set ${set} where id=$${use.length + 1}`,
    [...use.map(c => coerce(data[c.name], c.type)), id]);
  return (r.rowCount ?? 0) > 0;
}

// DELETE a record. Confined to the project schema; parameterized id.
export async function deleteRow(pool: pg.Pool, projectId: string, table: string, id: number): Promise<boolean> {
  const schema = schemaName(projectId);
  if (!IDENT.test(table) || !Number.isInteger(id) || !(await listTables(pool, projectId)).includes(table)) return false;
  const r = await pool.query(`delete from "${schema}"."${table}" where id=$1`, [id]);
  return (r.rowCount ?? 0) > 0;
}

// Columns of a table suitable for an "add a record" form: scalar user-fillable fields PLUS real
// relations (M2): a column with an actual FK constraint is returned with {ref, display} so the
// renderer emits a <select> of the referenced table's real records — the form matches the schema
// by construction, never hand-emitted. Non-FK `*_id` columns stay hidden (opaque numbers).
export async function formColumns(pool: pg.Pool, projectId: string, table: string, audience: ReadAudience = 'public'): Promise<{ name: string; type: string; nullable: boolean; ref?: string; display?: string }[]> {
  const schema = schemaName(projectId);
  if (!IDENT.test(table) || !(await listTables(pool, projectId)).includes(table)) return [];
  const fkMap = new Map<string, string>();
  try {
    const fks = (await pool.query(
      `select kcu.column_name as col, ccu.table_name as ref
       from information_schema.table_constraints tc
       join information_schema.key_column_usage kcu on kcu.constraint_name=tc.constraint_name and kcu.table_schema=tc.table_schema
       join information_schema.constraint_column_usage ccu on ccu.constraint_name=tc.constraint_name and ccu.table_schema=tc.table_schema
       where tc.constraint_type='FOREIGN KEY' and tc.table_schema=$1 and tc.table_name=$2`, [schema, table])).rows;
    for (const fk of fks) if (IDENT.test(fk.col) && IDENT.test(fk.ref) && fk.ref !== table) fkMap.set(fk.col, fk.ref);
  } catch {}
  const out: { name: string; type: string; nullable: boolean; ref?: string; display?: string }[] = [];
  for (const c of await typedColumns(pool, schema, table)) {
    if (['id', 'created_at'].includes(c.name) || SENSITIVE.test(c.name)) continue;
    if (audience !== 'owner' && SYSTEM_COLS.test(c.name)) continue;   // FS0: a visitor never fills "Status"
    const ref = fkMap.get(c.name);
    // a PUBLIC form never shows a dropdown into a private table — its read is sealed, so the options
    // would always be empty (compile makes these nullable, so omitting the field keeps inserts valid)
    if (ref && audience !== 'owner' && PRIVATE_READ.test(ref) && c.nullable) continue;
    if (ref) out.push({ ...c, ref, display: await displayColumn(pool, schema, ref) });
    else if (!/_id$/.test(c.name)) out.push(c);
  }
  return out;
}

// INTROSPECTION — the system knows the database: every table's columns/types, real relations, row counts.
// Read straight from the catalog of the project's own schema. Powers the data API, the build agent, and
// the project workspace's "Database" view.
export async function describeSchema(pool: pg.Pool, projectId: string): Promise<{ schema: string; tables: any[] }> {
  const schema = schemaName(projectId);
  const tabs = await listTables(pool, projectId);
  const tables: any[] = [];
  for (const t of tabs) {
    const cols = (await pool.query(
      'select column_name, data_type, is_nullable from information_schema.columns where table_schema=$1 and table_name=$2 order by ordinal_position', [schema, t])).rows;
    const fks = (await pool.query(
      `select kcu.column_name as col, ccu.table_name as ref
       from information_schema.table_constraints tc
       join information_schema.key_column_usage kcu on kcu.constraint_name=tc.constraint_name and kcu.table_schema=tc.table_schema
       join information_schema.constraint_column_usage ccu on ccu.constraint_name=tc.constraint_name and ccu.table_schema=tc.table_schema
       where tc.constraint_type='FOREIGN KEY' and tc.table_schema=$1 and tc.table_name=$2`, [schema, t])).rows;
    let rows = 0; try { rows = Number((await pool.query(`select count(*)::int n from "${schema}"."${t}"`)).rows[0].n); } catch {}
    tables.push({
      table: t, rows,
      columns: cols.map((c: any) => ({ name: c.column_name, type: c.data_type, nullable: c.is_nullable === 'YES' })),
      relations: fks.map((f: any) => ({ column: f.col, references: f.ref })),
    });
  }
  return { schema, tables };
}
